### ISSUE TITLE
使用的朋友建个交流群互相解决问题吧

### ISSUE THREAD

**Issue by Liuxianguang1986** [huaisha1224/jd-assistant#10]

**Comment by Liuxianguang1986** [comment]
我的问题是获取不到库存，
skuId":100004774658,"choseSuit":[],"code":1,"err":true,"PopType":0,"ArrivalDate":null,"IsPurchase":false,"StockStateName":"有货","rn":-1}), exception: 'NoneType' object has no attribute 'get'
2021-09-11 21:49:30,429 INFO: 100004774658 不满足下单条件，5s后进行下一次查询

stock_info = resp_json.get('stock')这个地方获取后是none，但是是有库存 的

**Comment by YvoIovY** [comment]
楼主建个tg群吧

**Comment by Liuxianguang1986** [comment]
> 楼主建个tg群吧

不用tg，我问题解决了，查不到库存因为cookie失效了，程序判断是否登陆有点问题

**Comment by Liuxianguang1986** [comment]
可以用手机验证码登陆cookie替换一下 据说可以用一个月

**Comment by cxs13991120** [comment]
订单提交失败, 错误码：0, 返回信息：您选择的收货地址不支持当前的配送方式，请重新选择配送方式！(下单商品可能为第三方商品，将切换为普通发票进行尝试)

老哥，请问这个问题如何解决？？

**Comment by YvoIovY** [comment]
> 可以用手机验证码登陆cookie替换一下 据说可以用一个月

我看cookie文件是加密的，你替换成功了？

**Comment by YvoIovY** [comment]
除了tg群，QQ微信都是机器算法风控，说封就封，垃圾至极。

**Comment by Liuxianguang1986** [comment]
> 订单提交失败, 错误码：0, 返回信息：您选择的收货地址不支持当前的配送方式，请重新选择配送方式！(下单商品可能为第三方商品，将切换为普通发票进行尝试)
> 
> 老哥，请问这个问题如何解决？？

这个是提交订单失败了，是地址或者发票问题导致的，你把self._save_invoice()放到下单前，下面这样试试
try:
            self._save_invoice()
            resp = self.sess.post(url=url, data=data, headers=headers)
