### ISSUE TITLE
3.1.3报错

### ISSUE THREAD

**Issue by tansuo8** [huaisha1224/jd-assistant#20]
3.1.1和3.1.2运行正常，3.1.3就没正常过一次。3.1.3报错如下：
2021-10-05 17:21:50,952 INF0：登录成功
2021-10-05 17:21:50,952 INF0：下单模式：[ 100014348492 〕任一商品有货并且末下架均会尝试下单
2021-10-05 17:21:51,445 ERROR： 查询 100014348492 库存信息发生异常，resp: jQuery6961229（f" StockState" :33,”area": f"townName":mm,"provinceName "：“北京","cityName " ："朝阳区
, "success": true, "countyName":"=FIr"}, "realSkuId":100014348492, "choseSuit": [], "code":1, "err": true, "PopType":©, "ArrivalDate":null, "IsPurchase": false,
"StockStateName": "A#", "rn": -1}), exception: 'NoneType' object has no attribute
请问何解![image](https://user-images.githubusercontent.com/91852022/136061262-950b984e-6a19-4210-855a-6e051ab15054.jpeg)

**Comment by huaisha1224** [comment]
https://item.jd.com/100014348492.html这个商品我测试了一下正常的
![image](https://user-images.githubusercontent.com/3378350/136314403-0743b257-a042-4174-83fc-68d93f298422.png)


1，区域ID一定要按照你收货地址来填写，如果不知区域id请在area_id目录下找到你所在的城市和区县，拿到后面的数字
2，默认收货地址调整为和你设置的区域id在同一个地区
3，建议删除cookies重新扫描登录

**Comment by myinlg** [comment]
> 3.1.1和3.1.2运行正常，3.1.3就没正常过一次。3.1.3报错如下： 2021-10-05 17:21:50,952 INF0：登录成功 2021-10-05 17:21:50,952 INF0：下单模式：[ 100014348492 〕任一商品有货并且末下架均会尝试下单 2021-10-05 17:21:51,445 ERROR： 查询 100014348492 库存信息发生异常，resp: jQuery6961229（f" StockState" :33,”area": f"townName":mm,"provinceName "：“北京","cityName " ："朝阳区 , "success": true, "countyName":"=FIr"}, "realSkuId":100014348492, "choseSuit": [], "code":1, "err": true, "PopType":©, "ArrivalDate":null, "IsPurchase": false, "StockStateName": "A#", "rn": -1}), exception: 'NoneType' object has no attribute 请问何解![image](https://user-images.githubusercontent.com/91852022/136061262-950b984e-6a19-4210-855a-6e051ab15054.jpeg)



> [https://item.jd.com/100014348492.html这个商品我测试了一下正常的](https://item.jd.com/100014348492.html%E8%BF%99%E4%B8%AA%E5%95%86%E5%93%81%E6%88%91%E6%B5%8B%E8%AF%95%E4%BA%86%E4%B8%80%E4%B8%8B%E6%AD%A3%E5%B8%B8%E7%9A%84) ![image](https://user-images.githubusercontent.com/3378350/136314403-0743b257-a042-4174-83fc-68d93f298422.png)
> 
> 1，区域ID一定要按照你收货地址来填写，如果不知区域id请在area_id目录下找到你所在的城市和区县，拿到后面的数字 2，默认收货地址调整为和你设置的区域id在同一个地区 3，建议删除cookies重新扫描登录
你好

> [https://item.jd.com/100014348492.html这个商品我测试了一下正常的](https://item.jd.com/100014348492.html%E8%BF%99%E4%B8%AA%E5%95%86%E5%93%81%E6%88%91%E6%B5%8B%E8%AF%95%E4%BA%86%E4%B8%80%E4%B8%8B%E6%AD%A3%E5%B8%B8%E7%9A%84) ![image](https://user-images.githubusercontent.com/3378350/136314403-0743b257-a042-4174-83fc-68d93f298422.png)
> 
> 1，区域ID一定要按照你收货地址来填写，如果不知区域id请在area_id目录下找到你所在的城市和区县，拿到后面的数字 2，默认收货地址调整为和你设置的区域id在同一个地区 3，建议删除cookies重新扫描登录

你好大佬，我也遇到楼主一模一样的情况，按照你的提示cookie也删了，地址也是对的，还是报错跟楼主一模一样，请问怎么解决
