### ISSUE TITLE
商品有货，提示库存信息发生异常，地址显示北京朝阳

### ISSUE THREAD

**Issue by myinlg** [huaisha1224/jd-assistant#21]
商品测试链接：https://item.jd.com/69826773961.html
areaid正常
![image](https://user-images.githubusercontent.com/37045183/137425391-dd24e938-2721-4968-8206-9c7fed6b35a7.png)

**Comment by a459118272** [comment]
同问

**Comment by huaisha1224** [comment]
![image](https://user-images.githubusercontent.com/3378350/140953731-7f2adf1f-1e65-49b1-b4e6-f5afbc9fd081.png)
商品测试链接：https://item.jd.com/69826773961.html
这个商品我这边测试可以正常下单。
