### ISSUE TITLE
二维码扫描后登录不上了。。。

### ISSUE THREAD

**Issue by chineseluo** [huaisha1224/jd-assistant#25]
生成的二维码，京东APP不识别

**Comment by huaisha1224** [comment]
1、在京东APP上退出账号然后重新登录京东APP
2、重新扫描二维码即可登录

**Comment by chineseluo** [comment]
大佬，有基地吗，还是扫描不识别，不知道为啥

**Comment by huaisha1224** [comment]
如果还是不京东APP还是识别失败
1、删除程序目录下的QRcode.png文件
2、重新运行程序
3、把用京东APP升级到最新版本

我这边测试了iOS以及安卓最新版本的京东APP都是可以正常扫码登录。
