### ISSUE TITLE
商品有货，提示库存信息发生异常

### ISSUE THREAD

**Issue by bestway66** [huaisha1224/jd-assistant#26]
![1642403661(1)](https://user-images.githubusercontent.com/92979691/149724080-c1307db3-0b9b-45c2-a54b-f7d92a98bed7.png)

-

**Comment by huaisha1224** [comment]
![image](https://user-images.githubusercontent.com/3378350/149731559-55d54d24-e6ed-458f-a914-f86d6fb023f0.png)

这个商品：https://item.jd.com/69826773961.html
是可以下单的呀。

**Comment by huaisha1224** [comment]
![image](https://user-images.githubusercontent.com/3378350/149731745-85690f55-1d90-4d14-9de7-74c215b05b4c.png)

商品：https://item.jd.com/69826773961.html

**Comment by bestway66** [comment]
> ![图片](https://user-images.githubusercontent.com/3378350/149731745-85690f55-1d90-4d14-9de7-74c215b05b4c.png)
> 
> 商品：https://item.jd.com/69826773961.html

已经解决了，还有那个预约抢购函数exec_reserve_seckill_by_time是不是不能自动预约呢

**Comment by foreverlong** [comment]
请问是如何解决的呢？
