### ISSUE TITLE
eid fp

### ISSUE THREAD

**Issue by Healer-sys** [huaisha1224/jd-assistant#32]
![image](https://user-images.githubusercontent.com/70415462/154792026-f69ed0f1-a3a7-429f-a8a3-ffb400f8d654.png)
是这个值吗，配置好了也是用不了😂😂😂
![image](https://user-images.githubusercontent.com/70415462/154792121-884797a4-20b2-482f-99ad-f9d8edbb4f83.png)

**Comment by huaisha1224** [comment]
eid和fp就是你取到的哪一个
risk_control也需要填写
