### ISSUE TITLE
订单提交失败, 错误码：0, 返回信息：获取用户订单信息失败(下单商品可能为第三方商品，将切换为普通发票进行尝试)

### ISSUE THREAD

**Issue by jimmg5202** [huaisha1224/jd-assistant#34]
商品编号：100021558776  一直提示错误

**Comment by huaisha1224** [comment]
京东国际的商品 需要改一下代码才行

**Comment by buildcold** [comment]
我也遇到这个问题，能支持京东国际就好了，能指点下思路改哪里么？

**Comment by ImCa0** [comment]
> 京东国际的商品 需要改一下代码才行

请问需要修改哪里的代码呀

**Comment by ImCa0** [comment]
找到解决方法了，在提交订单前手动修改一下配送方式（我的是京东自营），并且提交订单时带上 `'overseaMerge': 1` 的参数

https://github.com/ImCa0/jd-assistant/commit/1f7f9ba25a89b43c42647c9097b84a2975febd88#diff-872daefd034547eba2ec5464a0042b1ed4bd414720a174bdce2b6cd7e2d1e993
