### ISSUE TITLE
有问题运行报错

### ISSUE THREAD

**Issue by yejinson** [huaisha1224/jd-assistant#37]
<img src='https://s2.loli.net/2022/06/03/lTXV4Kx7gky9r15.png' title='quicker_de59e118-a142-44e6-a800-2753cc637420.png' />

**Comment by yejinson** [comment]
有没大神知道咋解决啊

**Comment by huaisha1224** [comment]
图片打不开呀

**Comment by yejinson** [comment]
> 图片打不开呀
图片挂了，没问题了谢谢。
