### ISSUE TITLE
请问大佬，怎么获取track_id，risk_control？

### ISSUE THREAD

**Issue by geniuskai** [huaisha1224/jd-assistant#4]
在控制台执行js报错，也没找到这两个的值，请问大佬该怎么获取

**Comment by huaisha1224** [comment]
在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl

**Comment by geniuskai** [comment]
搜到了，但是没有值



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月8日(周三) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huaisha1224/jd-assistant] 请问大佬，怎么获取track_id，risk_control？ (#4)




 
在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Supermanhu** [comment]
> 在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl

可否详细告知怎么获取，订单支付页面是京东收银台页面选好支付方式的页面么，在此页面的查看器中我只找到了一个函数( getJdEid(function(eid, fp, risk)), network页面中搜索不到这四个参数中的任何一个。
