### ISSUE TITLE
作者借鉴的时间同步的代码是改了接口的，但是作者只copy了timer.py的代码,所以会出错

### ISSUE THREAD

**Issue by cxs13991120** [huaisha1224/jd-assistant#7]
有什么办法解决吗？？没改时间之前的版本，可以正常运行，这个版本一直闪退，无法正常使用

**Comment by YvoIovY** [comment]
> 有什么办法解决吗？？没改时间之前的版本，可以正常运行，这个版本一直闪退，无法正常使用

怎么回滚到上个版本？

**Comment by huaisha1224** [comment]
我回退版本了、更新一下。
也可以只下载timer.py

**Comment by KindJinrong** [comment]
def jd_time(self):
        """
        从京东服务器获取时间毫秒
        :return:
        """
        r1 = requests.get(url='https://api.m.jd.com/client.action?functionId=queryMaterialProducts&client=wh5',
                          headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'})

        x = eval(r1.text)
        timeNum = int(x['currentTime2'])
        return timeNum

**Comment by KindJinrong** [comment]
> def jd_time(self): """ 从京东服务器获取时间毫秒 :return: """ r1 = requests.get(url='https://api.m.jd.com/client.action?functionId=queryMaterialProducts&client=wh5', headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'})
> 
> ```
>     x = eval(r1.text)
>     timeNum = int(x['currentTime2'])
>     return timeNum
> ```

京东服务器 获取地址的api接口变了，我找的结局方案。作者如果有空希望，可以帮忙添加一下这个功能。
